spring.cloud.gateway.server.webflux.routes[0].id=PRODUCTSERVICEE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCTSERVICEE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/product/**

spring.cloud.gateway.server.webflux.routes[1].id=ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**

spring.cloud.gateway.server.webflux.routes[2].id=PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payment/**
